import React from 'react';
import { Complaint } from '../types';
import { FileText, ShieldCheck, Landmark, Printer, Download, Receipt, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface MunicipalInvoiceProps {
  funding: NonNullable<Complaint['funding']>;
  department: string;
  category: string;
  caseId: string;
  title: string;
  status?: Complaint['status'];
}

export default function MunicipalInvoice({ funding, department, category, caseId, title, status }: MunicipalInvoiceProps) {
  const handlePrint = (e: React.MouseEvent) => {
    e.preventDefault();
    window.print();
  };

  const isApproved = status && ['acknowledged', 'scheduled', 'repairing', 'repaired_audit', 'resolved'].includes(status);

  // 18% GST (9% CGST & 9% SGST) is standard in Indian municipal contract billing
  const baseValue = Math.round(funding.totalBudget / 1.18);
  const totalTax = funding.totalBudget - baseValue;
  const cgst = Math.round(totalTax / 2);
  const sgst = totalTax - cgst; // Balance to prevent rounding mismatches

  return (
    <div 
      className={`border rounded-2xl p-6 shadow-sm flex flex-col gap-6 relative overflow-hidden text-slate-800 font-sans transition-all duration-300 ${
        isApproved 
          ? "bg-gradient-to-br from-white via-slate-50 to-emerald-50/25 border-emerald-200" 
          : "bg-slate-50 border-slate-200"
      }`} 
      id={`municipal-tax-invoice-${funding.invoiceNumber}`}
    >
      {/* Background Watermark/Emblem Accent */}
      <div className="absolute right-[-20px] bottom-[-20px] opacity-[0.03] pointer-events-none select-none">
        <Landmark className="w-64 h-64 text-slate-900" />
      </div>

      {/* Invoice Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 border-b border-slate-200 pb-5">
        <div className="flex items-start gap-3">
          <div className={`p-2.5 rounded-xl shadow-xs shrink-0 text-white transition-colors duration-300 ${
            isApproved ? "bg-emerald-600 shadow-emerald-100" : "bg-amber-600 shadow-amber-100"
          }`}>
            <Receipt className="w-6 h-6" />
          </div>
          <div>
            <span className={`text-[10px] font-black tracking-widest uppercase font-mono block ${
              isApproved ? "text-emerald-700" : "text-amber-700"
            }`}>
              {isApproved ? "Official Municipal Ledger" : "Pro-Forma Dispatch Ledger"}
            </span>
            <h4 className="text-base font-extrabold text-slate-800 font-display mt-0.5">
              {isApproved ? "Real Municipal Invoice" : "AI-Generated Approximate Invoice"}
            </h4>
            <p className="text-[10.5px] text-slate-500 mt-0.5 font-medium">
              {isApproved 
                ? "Real Invoice Shared and Confirmed by Respective Department" 
                : "Social Constraint Audited Project Estimate"
              }
            </p>
          </div>
        </div>

        <div className="text-left md:text-right flex flex-col gap-1 font-mono">
          <div className="text-[11px] text-slate-500">
            Invoice ID: <span className="text-slate-800 font-extrabold">{funding.invoiceNumber}</span>
          </div>
          <div className="text-[11px] text-slate-500">
            Case Ref: <span className="text-slate-800 font-bold">{caseId}</span>
          </div>
          <div className="text-[11px] text-slate-500">
            F.Y.: <span className="text-slate-800 font-bold">2026-2027</span>
          </div>
        </div>
      </div>

      {/* Disclaimer / Approval Banner */}
      {!isApproved ? (
        <div className="bg-amber-50/90 border border-amber-200/80 text-amber-900 rounded-xl p-4 text-xs flex gap-3 items-start shadow-2xs" id="disclaimer-approximate">
          <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
          <div>
            <span className="font-extrabold block text-[11px] uppercase tracking-wider mb-0.5 text-amber-950 font-display">
              ⚠️ Approximate AI-Generated Invoice
            </span>
            <p className="text-slate-600 font-medium leading-relaxed">
              <b>Disclaimer:</b> This is an approximate cost estimate automatically generated by the regional AI system based on visual proofs, community metrics, and standard municipal materials indexes. Actual procurement budgets shared by the respective department may vary upon physical site inspection and final engineering approval.
            </p>
          </div>
        </div>
      ) : (
        <div className="bg-emerald-50/90 border border-emerald-200/80 text-emerald-900 rounded-xl p-4 text-xs flex gap-3 items-start shadow-2xs" id="municipal-invoice-shared">
          <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5 animate-pulse" />
          <div>
            <span className="font-extrabold block text-[11px] uppercase tracking-wider mb-0.5 text-emerald-950 font-display">
              ✅ Confirmed Real Municipal Invoice
            </span>
            <p className="text-slate-600 font-medium leading-relaxed">
              The respective department <b>{department}</b> has approved to process this neighborhood problem and shared this official municipal invoice. Funding has been successfully allocated from municipal development budgets for site execution.
            </p>
          </div>
        </div>
      )}

      {/* Invoice Details Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 bg-white border border-slate-150 p-4 rounded-xl shadow-2xs">
        <div>
          <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 block font-mono">Authorized Body</span>
          <span className="text-xs font-bold text-slate-700 block mt-1 leading-tight">{department}</span>
        </div>
        <div>
          <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 block font-mono">Work Class</span>
          <span className="text-xs font-bold text-slate-700 block mt-1 leading-tight">{category}</span>
        </div>
        <div>
          <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 block font-mono">Sanction Code</span>
          <span className="text-xs font-bold text-slate-700 block mt-1 leading-tight font-mono text-emerald-700">SC-{funding.invoiceNumber.split('-')[1] || 'V2'}</span>
        </div>
        <div>
          <span className="text-[9px] font-black uppercase tracking-wider text-slate-400 block font-mono">Audit Status</span>
          <span className={`inline-flex items-center gap-1 text-[10px] font-extrabold px-2 py-0.5 rounded-md border mt-1 ${
            isApproved 
              ? "text-emerald-700 bg-emerald-50 border-emerald-100 animate-pulse" 
              : "text-amber-700 bg-amber-50 border-amber-100"
          }`}>
            <ShieldCheck className="w-3.5 h-3.5" />
            {isApproved ? "Real Shared Invoice" : "Vetted Approximate Bill"}
          </span>
        </div>
      </div>

      {/* Itemized Table */}
      <div className="flex flex-col">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 text-slate-400 font-bold text-[10px] uppercase tracking-wider">
                <th className="py-2.5 px-1 w-8 text-center">#</th>
                <th className="py-2.5 px-2">Remediation Resource / Quantity Spec</th>
                <th className="py-2.5 px-2 text-right">Cost Category</th>
                <th className="py-2.5 px-2 text-right w-28">Amount (₹)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {/* Itemized Materials Breakdown */}
              {funding.materialsBreakdown && funding.materialsBreakdown.map((item, idx) => (
                <tr key={idx} className="hover:bg-slate-100/40 transition-colors">
                  <td className="py-2 px-1 text-center font-mono text-[10.5px] text-slate-400">{idx + 1}</td>
                  <td className="py-2 px-2 font-medium text-slate-700">{item.name}</td>
                  <td className="py-2 px-2 text-right text-[11px] text-slate-400 italic">Direct Materials</td>
                  <td className="py-2 px-2 text-right font-mono font-medium text-slate-700">₹{item.cost.toLocaleString()}</td>
                </tr>
              ))}

              {/* Labor Component */}
              <tr className="hover:bg-slate-100/40 transition-colors">
                <td className="py-2 px-1 text-center font-mono text-[10.5px] text-slate-400">{funding.materialsBreakdown.length + 1}</td>
                <td className="py-2 px-2 font-medium text-slate-700">
                  Technical field engineers, hazardous safety workforce & site coordination hours
                </td>
                <td className="py-2 px-2 text-right text-[11px] text-slate-400 italic">Technical Labor</td>
                <td className="py-2 px-2 text-right font-mono font-medium text-slate-700">₹{funding.laborCost.toLocaleString()}</td>
              </tr>

              {/* Equipment Component */}
              <tr className="hover:bg-slate-100/40 transition-colors">
                <td className="py-2 px-1 text-center font-mono text-[10.5px] text-slate-400">{funding.materialsBreakdown.length + 2}</td>
                <td className="py-2 px-2 font-medium text-slate-700">
                  Heavy logistics, utility site truck rental, specialized diagnostic sensors & safety barricades
                </td>
                <td className="py-2 px-2 text-right text-[11px] text-slate-400 italic">Equipment hire</td>
                <td className="py-2 px-2 text-right font-mono font-medium text-slate-700">₹{funding.equipmentCost.toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Calculations & Totals Summary */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 pt-2 border-t border-slate-200">
        {/* Quality Certification Stamp */}
        <div className="flex flex-col gap-3 max-w-sm w-full">
          {funding.meta && (
            <div className="flex flex-col gap-1.5 p-3.5 bg-sky-50 border border-sky-100 rounded-xl">
              <span className="text-[9px] font-black text-sky-800 tracking-wider uppercase font-mono block">
                Government Lake Audit Parameters
              </span>
              <div className="grid grid-cols-2 gap-x-3 gap-y-1 text-[10.5px] font-medium text-sky-700 font-mono">
                <div>Est. Lake Size:</div>
                <div className="font-bold text-right text-sky-900">{funding.meta.areaHectares} Hectares</div>
                <div>Pollution Severity:</div>
                <div className="font-bold text-right text-sky-900">{funding.meta.pollutionLevel}</div>
                <div>Industrial Zone:</div>
                <div className="font-bold text-right text-sky-900">{funding.meta.nearIndustrialZone ? "Yes (+40% Surcharge)" : "No"}</div>
                <div className="border-t border-sky-200/60 pt-1 mt-1 col-span-2 flex justify-between font-sans text-xs">
                  <span className="font-bold text-sky-800">Total Outlay:</span>
                  <span className="font-black text-sky-900">₹{funding.meta.totalBudgetCrores} Crores</span>
                </div>
              </div>
            </div>
          )}

          {isApproved ? (
            <div className="flex flex-col gap-1.5 p-3.5 bg-emerald-50 border border-emerald-100 rounded-xl relative overflow-hidden shadow-2xs">
              <span className="text-[9px] font-black text-emerald-800 tracking-wider uppercase font-mono block">
                Official Department Authorization
              </span>
              <p className="text-[10px] text-emerald-750 leading-relaxed font-medium">
                This invoice has been officially processed, approved, and authorized for public release by the respective finance division of <b>{department}</b>.
              </p>
              <div className="mt-1 pt-1.5 border-t border-emerald-100/60 flex items-center justify-between text-[9px] text-emerald-600 font-mono font-bold">
                <span>Digital Sign: DEPT-EXEC-SEC</span>
                <span className="text-[9px] rotate-[-4deg] border border-emerald-600 px-1 py-0.5 rounded font-black tracking-widest text-emerald-750 bg-white">APPROVED</span>
              </div>
            </div>
          ) : (
            <div className="flex flex-col gap-1.5 p-3.5 bg-amber-50 border border-amber-100 rounded-xl shadow-2xs">
              <span className="text-[9px] font-black text-amber-800 tracking-wider uppercase font-mono block">
                Approximate AI Estimate
              </span>
              <p className="text-[10px] text-amber-700 leading-relaxed font-medium">
                This is a pro-forma approximate citizen bill, generated to aid speed of legal routing and official public interest filing. Actual figures are subject to change.
              </p>
            </div>
          )}
        </div>

        {/* Totals Summary */}
        <div className="w-full md:w-72 flex flex-col gap-1.5 text-xs text-slate-600 font-mono">
          <div className="flex justify-between pb-1 border-b border-slate-150">
            <span>Subtotal (Net Value):</span>
            <span>₹{baseValue.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-slate-500 text-[11px] pb-0.5">
            <span>CGST (9.0%):</span>
            <span>₹{cgst.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-slate-500 text-[11px] pb-1 border-b border-slate-150">
            <span>SGST (9.0%):</span>
            <span>₹{sgst.toLocaleString()}</span>
          </div>
          <div className="flex justify-between items-baseline pt-1 text-slate-900">
            <span className="text-xs font-black uppercase font-sans tracking-wide">Grand Total:</span>
            <span className="text-lg font-black text-emerald-700">₹{funding.totalBudget.toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* Printable utility footer */}
      <div className="flex items-center justify-between border-t border-slate-200 pt-4 mt-2">
        <span className="text-[9.5px] text-slate-400 font-mono">
          {isApproved 
            ? "* Real Municipal Tax Invoice shared and authorized by respective department."
            : "* Tax Invoice generated automatically via regional AI visual audit system (approximate)."
          }
        </span>
        <div className="flex gap-2">
          <button
            onClick={handlePrint}
            className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-all cursor-pointer"
            title="Print Municipal Invoice"
          >
            <Printer className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
